baseURL = "https://www.pruddieverse.com/"
languageCode = "en-us"
title = "Pruddieverse"
theme = "github.com/jpanther/congo/v2"
copyright = "2025 Prudence Anumudu"

[params]
  colorScheme = "ocean"
  favicon = "favicon.ico"
  customCss = ["css/custom.css"]

  [params.author]
    name = "Pruddie"
    image = "headshot.jpg"
    headline = "Cloud & DevOps Engineer"
    links = [
      { github = "https://github.com/Cwendee" },
      { linkedin = "https://www.linkedin.com/in/prudence-c-anumudu-35518656" },
      { email = "pruddyanumudu@gmail.com" }
    ]

  [params.homepage]
    layout = "hero"
    showRecent = true

  [params.header]
    layout = "classic"

  [params.footer]
    showCopyright = true
    showPoweredBy = false
