baseURL = "https://www.pruddieverse.com/"
theme = "congo"
title = "Pruddieverse"

[params]
  favicon = "favicon.png"
  # This stops the theme from automatically adding sections we don't want
  disableHomeCollections = true 

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30
