baseURL = "https://www.pruddieverse.com/"
languageCode = "en-us"
title = "Pruddieverse"

[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"

[params]
  # Theme Customization
  colorScheme = "emerald" # Options: coffee, ocean, forest, blowfish, slate
  fontFamily = "inter"
  
  # Branding
  description = "Cloud & DevOps Engineer | Architecting the Pruddieverse"
  
  [params.homepage]
    layout = "hero"
    showRecent = false

  [params.hero]
    title = "Building the Pruddieverse."
    subtitle = "Cloud & DevOps Engineer specializing in Scalable Infrastructure."
    image = "headshot.jpg" # We will add this file later!

  # Social Links (This adds the icons recruiters look for!)
  [[params.author.links]]
    github = "https://github.com/Cwendee"
    linkedin = "https://www.linkedin.com/in/prudence-c-anumudu-35518656/" # Update this!
    email = "pruddyanumudu@gmail.com"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
