baseURL = "https://www.pruddieverse.com/"
languageCode = "en-us"
title = "Pruddieverse"

[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"

[params]
  colorScheme = "blowfish"
  
  [params.homepage]
    layout = "hero"
    showRecent = false

  [params.hero]
    title = "Building the Pruddieverse."
    subtitle = "Cloud & DevOps Engineer"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
