baseURL = "https://www.pruddieverse.com/"
languageCode = "en-us"
title = "Pruddieverse"
theme = "github.com/jpanther/congo/v2"

[params]
  colorScheme = "ocean"
  # This fixes the Favicon and Headshot
  favicon = "favicon.ico"
  customCss = ["css/custom.css"]

  [params.author]
    name = "Pruddie"
    # Ensure this file is inside your 'static/' folder
    image = "headshot.jpg" 
    headline = "Cloud & DevOps Engineer"
    bio = "Building the Pruddieverse."

  [params.homepage]
    layout = "hero"
    showRecent = true

  [params.header]
    layout = "classic"
