baseURL = "https://www.pruddieverse.com/"
languageCode = "en-us"
title = "Pruddieverse"
theme = "github.com/jpanther/congo/v2"
copyright = "2025 Prudence Anumudu"

# This is the "Magic" fix for the plain HTML text issue
relativeURLs = true
canonifyURLs = true

[params]
  colorScheme = "ocean"
  favicon = "favicon.ico"
  customCss = ["css/custom.css"]

  [params.author]
    name = "Pruddie"
    image = "headshot.jpg"
    headline = "Cloud & DevOps Engineer"
    links = [
      { github = "https://github.com/Cwendee" },
      { linkedin = "https://www.linkedin.com/in/prudence-c-anumudu-35518656" },
      { email = "mailto:pruddyanumudu@gmail.com" }
    ]

  [params.header]
    layout = "classic"

  [params.footer]
    showCopyright = true
    center = true

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
