baseURL = "https://www.pruddieverse.com/"
languageCode = "en-us"
title = "Pruddieverse"
theme = "github.com/jpanther/congo/v2"
copyright = "2025 Prudence Anumudu"

[params]
  colorScheme = "ocean"
  # This makes the font straight and fixes spacing
  customCss = ["css/custom.css"]
  
  [params.header]
    layout = "basic"

  [params.footer]
    showCopyright = true

  [params.homepage]
    layout = "hero"
    showRecent = true

  [params.author]
    name = "Pruddie"
    image = "headshot.jpg"
    headline = "Cloud & DevOps Engineer | Automating Infrastructure."
    bio = "Building the Pruddieverse."

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
