baseURL = "https://www.pruddieverse.com/"
languageCode = "en-us"
title = "Pruddieverse"
theme = "congo"
copyright = "2025 Prudence Anumudu"

[params]
  colorScheme = "ocean"
  favicon = "favicon.png"
  customCss = ["css/custom.css"]

  [params.author]
    name = "Pruddie"
    image = "headshot.jpg"
    headline = "Cloud & DevOps Engineer"
    bio = "Building the Pruddieverse."
    links = [
      { github = "https://github.com/Cwendee" },
      { linkedin = "https://www.linkedin.com/in/prudence-c-anumudu-35518656" },
      { email = "mailto:pruddyanumudu@gmail.com" }
    ]

  [params.footer]
    showCopyright = true
    showPoweredBy = true
    center = true 

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
