baseURL = "https://www.pruddieverse.com/"
languageCode = "en-us"
title = "Pruddieverse"
copyright = "2025 Prudence Anumudu"

[params]
  colorScheme = "ocean"
  customCSS = ["css/custom.css"]
  
  [params.author]
    name = "Pruddie"
    image = "headshot.jpg" 

  [params.homepage]
    layout = "hero"

  [params.hero]
    title = "Building the Pruddieverse."
    subtitle = "Cloud & DevOps Engineer | Automating Infrastructure."

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
